# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Include the entire homeassistant block from a separate file.
# This file now contains URLs AND the packages directory definition.
homeassistant: !include homeassistant.yaml

# Include HTTP proxy settings from a separate, local-only file.
http: !include http.yaml

# Take control of the user interface (Lovelace) in YAML mode.
# This tells Home Assistant to load its main dashboard configuration
# from the 'ui-lovelace.yaml' file.
lovelace:
  mode: yaml
  # In YAML mode, resources must be declared here in the main configuration
  # so they are loaded before the UI is rendered.
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module

# All other configurations (mqtt, input_number, script, automation, etc.)
# are now defined within the files in the 'packages' directory.
# This main configuration file should remain clean and simple.
